version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: jobmatch-postgres
    environment:
      POSTGRES_USER: jobmatch
      POSTGRES_PASSWORD: jobmatch
      POSTGRES_DB: jobmatch
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build: ./backend/user-service
    container_name: jobmatch-user-service
    ports:
      - "8081:8080"
    env_file:
      - .env.user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobmatch
      SPRING_DATASOURCE_USERNAME: jobmatch
      SPRING_DATASOURCE_PASSWORD: jobmatch
    depends_on:
      - postgres

  job-service:
    build: ./backend/job-service
    container_name: jobmatch-job-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobmatch
      SPRING_DATASOURCE_USERNAME: jobmatch
      SPRING_DATASOURCE_PASSWORD: jobmatch
    depends_on:
      - postgres

  matching-service:
    build: ./backend/matching-service
    container_name: jobmatch-matching-service
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobmatch
      SPRING_DATASOURCE_USERNAME: jobmatch
      SPRING_DATASOURCE_PASSWORD: jobmatch
    depends_on:
      - postgres

volumes:
  pgdata:
