spring:
  application:
    name: job-service
  datasource:
    url: jdbc:postgresql://localhost:5433/jobmatch
    username: jobmatch
    password: jobmatch
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080
